name: Compliance Scan
on: [push, pull_request]
jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Dependency Audit
        run: npm audit --audit-level=high
